### PR TITLE
feat: dockerfile

### PR DESCRIPTION
**Pull request by kasefuchs**
docker go brrr

### CODE REVIEW

**Comment by forscht** [comment]
@kasefuchs 

1. Could you please consider using the latest Alpine (official) as the base instead of Debian?
2. In order to ensure consistency between the build process of `ddrv` and the Docker build, it would be helpful to add a command in the Makefile. This will help us remember to update the Docker build command whenever changes are made to `ddrv`. Could you please consider adding a new target called `build-docker` in the Makefile? This would greatly enhance the maintainability of our project.

**Comment by kasefuchs** [comment]
@forscht 
1. I think its possible, but then Ill have to disable CGO. Is it also possible to use a `scratch` image as base instead of Alpine(and Debian)?
2. Makefile already has this command, but it mentions `ditto` as the image name, should I change that to the actual project name? https://github.com/forscht/ddrv/blob/bfc51841cd0c1b004007e592c9f7617cb5408856/Makefile#L18-L20

**Comment by forscht** [comment]
1. ddrv doesn't require cgo do you can disable it. Yes use scratch image ( I didn't know about it earlier thanks!).
2. Projects old name was ditto change it to ddrv and change that Target name to `build-docker-image` 
3. Add new target called `build-docker` and call `make docker-build` in Dockerfile

**Comment by forscht** [comment]
@kasefuchs Have you try building the ddrv? So I can close this PR

**Comment by kasefuchs** [comment]
Builded on `Ubuntu Server 22.04`:
image

**Comment by forscht** [comment]
@kasefuchs Thanks, Merging.

**Pull request merged**
